apiVersion: v1
kind: Service
metadata:
  name: fuzi-search
  namespace: fuzi
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30103
  selector:
     app: fuzi-search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzi-search
  namespace: fuzi
spec:
  selector:
    matchLabels:
      app: fuzi-search
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzi-search
    spec:
      containers:
      - name: fuzi-search
        image: 192.168.2.101:5000/fuzi-search:1.0.0
        ports:
        - containerPort: 8082
